services:
  attendance-backend:
    image: huyquang/attendance-backend:latest
    container_name: attendance-backend
    command: python run.py
    network_mode: host
    volumes:
      - .:/app
      - /mnt/atin/huyquang/project-face/face-attendance/storage:/storage
    env_file:
      - ./resources/configs/.env
    restart: unless-stopped
    depends_on:
      - redis
      - celery-worker

  redis:
    image: redis:alpine
    ports:
      - "63079:6379"
    volumes:
      - redis_data:/data

  celery-worker:
    build: .
    command: celery -A app.core.celery.celery_app worker --loglevel=info
    network_mode: host
    volumes:
      - .:/app
      - /mnt/atin/huyquang/project-face/face-attendance/storage:/storage
    env_file:
      - ./resources/configs/.env
    depends_on:
      - redis

  file-server:
    image: python:3.9-slim
    command: python -m http.server 8080 --directory /storage/person-register
    volumes:
      - /mnt/atin/huyquang/project-face/face-attendance/storage:/storage
    ports:
      - "62012:8080"
  
  nginx:
    image: nginx:alpine
    network_mode: host
    ports:
      - "62001:62001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - file-server

volumes:
  redis_data:
