services:
  attendance-backend:
    image: huyquang/attendance-backend:latest
    container_name: attendance-backend
    command: python run.py
    network_mode: host
    volumes:
      - .:/app
    env_file:
      - ./resources/configs/.env
    restart: unless-stopped
    depends_on:
      - redis
      - celery-worker

  redis:
    image: redis:alpine
    ports:
      - "63079:6379"
    volumes:
      - redis_data:/data

  celery-worker:
    build: .
    command: celery -A app.core.celery.celery_app worker --loglevel=info
    network_mode: host
    volumes:
      - .:/app
    env_file:
      - ./resources/configs/.env
    depends_on:
      - redis

volumes:
  redis_data:
